### ISSUE TITLE
Async Operations Missing

### ISSUE THREAD

**Issue by nazarkryp** [cloudinary/CloudinaryDotNet#128]
I've installed latest package version 1.3.1.
ASP.NET Core 2.1 Project

I'd like to have UploadAsync(...) method. Instead I have Upload(...) only.

Please do not specify comments e.g: use Task.Run(...) etc.

**Comment by roeeba** [comment]
Hi @nazarkryp. Currently, this `UploadAsync` method is not supported for Core. We might support it going forward.

**Comment by MisterHoker** [comment]
I review asynchronous code and as I see current asynchronous methods (from .net framework) are senseless.


https://exceptionnotfound.net/two-ways-to-do-async-await-in-asp-net-wrong-and-how-to-fix-them/

**Comment by MisterHoker** [comment]
I review 'asynchronous code' and as I see current asynchronous methods (from .net framework library version) are senseless.

1. If invoke task.Wait() method become synchronous - current thread blocked until task become completed (this I saw in API class)
2. Event if we wrap synchronous code in TaskFactory.CreateNew (Like in partial class Cloudinary) this will not override internal synchronous code. So TaskScheduler will schedule synchronous task.

So in this case instead of using TPL's power is simply becomes ignored.
I post articles below to give more detailed explanation of issue:

https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/
https://exceptionnotfound.net/two-ways-to-do-async-await-in-asp-net-wrong-and-how-to-fix-them/

**Comment by michalpilarekfrisco** [comment]
It's quite important feature. Any updates on implementation progress?

**Comment by aditimadan-Cloudinary** [comment]
@michalpilarekfrisco The priority of the ticket has been bumped and will update the thread once the issue is fixed.

**Comment by michalpilarekfrisco** [comment]
Nuget version tagged 1.9.0 has dlls for netcore and netstandard1.3 with version 1.8.1, so the async operations are still missing for .Net Core

**Comment by roeeba** [comment]
Hi @michalpilarekfrisco. Thanks for letting us know. We will fix it and release a new version shortly.

**Comment by roeeba** [comment]
@michalpilarekfrisco. The issue was fixed. Would you mind trying version 1.9.1?

**Comment by michalpilarekfrisco** [comment]
Version 1.9.1 is working. Thank You for your effort!

**Comment by roeeba** [comment]
Good to hear @michalpilarekfrisco :)

Thanks for the update.
