### ISSUE TITLE
ListResources() returns only images and gifs

### ISSUE THREAD

**Issue by keskinonur11** [cloudinary/CloudinaryDotNet#155]
I have two video files (both mp4), can't get those from ListResources call. Is there any special method to get videos?

**Comment by igy** [comment]
Hi Onur,
If you don't specify any parameters, the default resource type returned is 'image'. If you're looking for videos and audio files, you'll need to specify this in the API call like this:

```
var listResourcesParams = new ListResourcesParams(){
  ResourceType = "video"};
var listResourcesResult = cloudinary.ListResources(listResourcesParams);
```
Can you please try that, and if it's still not working can you please provide an example that I can check?
Thanks,
Stephen

**Comment by keskinonur11** [comment]
Hello Stephen, 
Thanks for the fast response, it works :) I have two follow up questions: 
- Is there any specific reason why videos are not included in the parameterless call?
- With this call the returned objects "Tags" are null. (Could be related with issue 82)

**Comment by igy** [comment]
Hi Onur,
I'm not sure why the default is to include images only; if I were to guess I'd say it's for backward compatibility or legacy reasons, because of the three resource types we support (image, video, raw), image was the first, and is often considered the default in other places and documentation.

If I understand the scope of issue #82 correctly, that was mostly related to the methods used to add tags to videos and should be resolved since v 1.3.0 of the SDK (via this PR: https://github.com/cloudinary/CloudinaryDotNet/pull/90 ). 
Just to confirm, with ` ResourceType = "video"` you're getting the videos and their metadata returned, but not the tags which are visible in the Media Library for the same videos?

**Comment by keskinonur11** [comment]
Got you, could be. 
Yes exactly as you described. I got the videos and can see their metada but not their tags. The following are the only properties returning: "public_id", "format", "version", "resource_type", "type", "created_at", "bytes", "width" ,"height", "url", "secure_url"

**Comment by igy** [comment]
In the 'list resources API', the 'tags' parameter is also false by default, you need to specify this as 'true' to receive the tags in the response.
I'm afraid I don't have a .NET environment right now to verify, but the call to include the tags should be:
```
var listResourcesParams = new ListResourcesParams(){
  ResourceType = ResourceType.Video, Tags = true };
var listResourcesResult = cloudinary.ListResources(listResourcesParams);
```
If that's not correct let me know and I'll check it in a proper environement for you.

**Comment by igy** [comment]
Hi Onur,
I'm going to close this issue now, as it's been open for a long time and I believe my previous comment answered your question - if you have additional questions please let me know, or contact our support team via support.cloudinary.com
thanks!
