### ISSUE TITLE
ListResourcesByAssetFolder raising JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. error

### ISSUE THREAD

**Issue by ashugthub** [cloudinary/CloudinaryDotNet#327]
## Bug report for Cloudinary .NET SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots or Stack Trace (if applicable)
…

## OS and Version
- [ ] Linux
- [x] Windows
- [ ] macOS
- [ ] MultiPlatform

## Versions and Libraries (fill in the version numbers)
- Cloudinary .NET SDK version - 0.0.0
- .NET Core - 0.0.0
- .NET Framework - 0.0.0

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by aleksandar-cloudinary** [comment]
Hi @AshuBanctec - Thanks for reporting.

It sounds like the request you've made may have encountered an error so you didn't receive a JSON response from Cloudinary hence the exception.

Could you please share your cloud name, the code you are running that produces this error, and the values of all parameters you're passing as part of the method call? Based on that, we should be able to understand why you're running into it.

**Comment by Nandan-Wewhare** [comment]
> Hi @AshuBanctec - Thanks for reporting.
> 
> It sounds like the request you've made may have encountered an error so you didn't receive a JSON response from Cloudinary hence the exception.
> 
> Could you please share your cloud name, the code you are running that produces this error, and the values of all parameters you're passing as part of the method call? Based on that, we should be able to understand why you're running into it.

Cloud name: di9pa2kh9

Code:

`DotEnv.Load(options: new DotEnvOptions(probeForEnv: true));
cloudinary = new Cloudinary(Environment.GetEnvironmentVariable("CLOUDINARY_URL"));
cloudinary.Api.Secure = true;
var res = cloudinary.ListResourcesByAssetFolder(folderName);
return res;`

**Comment by igy** [comment]
Hi Nandan, 

From the details provided, we found a log of the underlying error returned to you, which was `folder decoupling is not enabled for customer`.

If you update your code to check for an error response from the API call you should see this on your side also.

The error is because the account you're calling the API for is using fixed folder mode, which does not have "asset folder" as a property of assets, and that's also why you can't call the  `ListResourcesByAssetFolder` method for that account.

Please see https://cloudinary.com/documentation/dynamic_folders for more information about the different folder modes - for fixed folder mode, you can make requests to other API methods to retrieve a list of assets in a folder (e.g. the Search API method, or [the 'prefix' option on the Get Resources method](https://cloudinary.com/documentation/admin_api#get_resources). 

We can also migrate an existing account to dynamic folders if you open a support request directly on our support site with the details.

Thanks,
Stephen
