### ISSUE TITLE
Retrieve image by public_id only without file extension

### ISSUE THREAD

**Issue by aibars** [cloudinary/CloudinaryDotNet#63]
Hi,

At some screen, I'm uploading images while completing a form and then saving the returned Public Ids that the API return on the database.
On another method, I'm trying to retrieve the signed URL by providing the public id, for example, "dev/pynin7oskrstrzahhfwz" to the following method:

`account.Api.UrlImgUp.Signed(true).BuildUrl("dev/pynin7oskrstrzahhfwz");`

While this method doesn't throw any exception, the result returns a 404 error:

`http://res.cloudinary.com/{cloudName}/image/upload/{signature}/v1/dev/{public id}`

It seems that I need to provide the file extension after the public id in order to get this signed url working.

Changing this to

`http://res.cloudinary.com/{cloudName}/image/upload/{signature}/v1/dev/{public id}.{fileExtension}`

works.

Is there a way to get the signed image URL by only providing the id? There could be some scenario where I cannot know which file type I should ask for.

**Comment by aibars** [comment]
Also, it would be nice that the method failed if the provided id is invalid.

**Comment by roeeba** [comment]
Hi, @aibars. The reason your code returns a 404 error is that all your resources have been uploaded as `authenticated` (type), while the default type requested on the API is `upload`. In order to get authenticated images, you need to explicitly set the `authenticated` type on your request. For example:
`cloudinary.Api.UrlImgUp.Action("authenticated").Signed(true).BuildUrl("dev/pynin7oskrstrzahhfwz"); `

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
